# Basic Information 
title: Anuvab Sen
position: PhD Candidate
affiliation: Georgia Institute of Technology
affiliation_link: https://www.gatech.edu/
affiliation_logo: ./assets/img/Georgia_Tech.png
email: asen74 (at) gatech.edu

# Search Engine Optimization (SEO)
keywords: anuvab sen, sen anuvab, anuvabsen, senanuvab
canonical: https://yaoyaoliu.web.illinois.edu
description: Anuvab Sen is a Ph.D. Candidate in the School of Electrical and Computer Engineering at the Georgia Institute of Technology in Atlanta, advised by Dr. Saibal Mukhopadhyay. My research focuses on developing simulation frameworks and design tools for quantum sensors aimed at low-power and precision-based applications.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=aQkZOqQAAAAJ
github_link: https://github.com/AnuvabSen1/
linkedin: https://www.linkedin.com/in/anuvabsen/
twitter: https://twitter.com/AnuvabSen10/
baseurl: "/anuvab_._sen"

# Images 
avatar: assets/img/Anuvab_Sen1.jpeg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/AnuvabSen1/anuvab_._sen

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
