# Basic Information 
title: Anuvab Sen
position: PhD Candidate
affiliation: Georgia Institute of Technology, Atlanta
affiliation_link: https://www.gatech.edu/
affiliation_logo: ./assets/img/GT.svg
email: asen74 (at) gatech.edu

# Search Engine Optimization (SEO)
keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
canonical: https://yaoyaoliu.web.illinois.edu
description: Yaoyao Liu is an assistant professor at the University of Illinois Urbana-Champaign. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=aQkZOqQAAAAJ
github_link: https://github.com/AnuvabSen1/
linkedin: https://www.linkedin.com/in/anuvabsen/
twitter: https://twitter.com/AnuvabSen10/

# Images 
avatar: ./assets/img/Anuvab_Sen1.jpeg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/AnuvabSen1/anuvab_._sen

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
